# mv -v -f ./dblot/system/app/AnalyticsCore /system/app/
# mv -v -f ./dblot/system/app/BasicDreams /system/app/
# mv -v -f ./dblot/system/app/Bluetooth /system/app/
# mv -v -f ./dblot/system/app/BluetoothMidiService /system/app/
# mv -v -f ./dblot/system/app/BookmarkProvider /system/app/
# mv -v -f ./dblot/system/app/CameraExtensionsProxy /system/app/
# mv -v -f ./dblot/system/app/CameraTest_J20C /system/app/
# mv -v -f ./dblot/system/app/CaptivePortalLoginGoogle /system/app/
# mv -v -f ./dblot/system/app/CarrierDefaultApp /system/app/
# mv -v -f ./dblot/system/app/CertInstaller /system/app/
# mv -v -f ./dblot/system/app/Cit /system/app/
# mv -v -f ./dblot/system/app/CloudService /system/app/
# mv -v -f ./dblot/system/app/CompanionDeviceManager /system/app/
# mv -v -f ./dblot/system/app/EasterEgg /system/app/
# mv -v -f ./dblot/system/app/facebook-appmanager /system/app/
# mv -v -f ./dblot/system/app/FidoAuthen /system/app/
# mv -v -f ./dblot/system/app/FidoClient /system/app/
# mv -v -f ./dblot/system/app/GFManager /system/app/
# mv -v -f ./dblot/system/app/GFTest_J20C /system/app/
# mv -v -f ./dblot/system/app/GoogleExtShared /system/app/
# mv -v -f ./dblot/system/app/GooglePrintRecommendationService /system/app/
# mv -v -f ./dblot/system/app/HTMLViewer /system/app/
# mv -v -f ./dblot/system/app/HybridAccessory /system/app/
# mv -v -f ./dblot/system/app/HybridPlatform /system/app/
# mv -v -f ./dblot/system/app/Joyose /system/app/
# mv -v -f ./dblot/system/app/KeyChain /system/app/
# mv -v -f ./dblot/system/app/LiveWallpapersPicker /system/app/
# mv -v -f ./dblot/system/app/MiCloudSync /system/app/
# mv -v -f ./dblot/system/app/MiConnectService /system/app/
# mv -v -f ./dblot/system/app/MIDrop /system/app/
# mv -v -f ./dblot/system/app/MiLinkGlobal /system/app/
# mv -v -f ./dblot/system/app/MIRadioGlobalBuiltin /system/app/
# mv -v -f ./dblot/system/app/MiSound /system/app/
# mv -v -f ./dblot/system/app/miui /system/app/
# mv -v -f ./dblot/system/app/MiuiAudioMonitor /system/app/
# mv -v -f ./dblot/system/app/MiuiBiometric /system/app/
# mv -v -f ./dblot/system/app/MiuiBluetooth /system/app/
# mv -v -f ./dblot/system/app/MiuiBugReport /system/app/
# mv -v -f ./dblot/system/app/MIUICalculatorGlobal /system/app/
# mv -v -f ./dblot/system/app/MIUICompassGlobal /system/app/
# mv -v -f ./dblot/system/app/MiuiDaemon /system/app/
# mv -v -f ./dblot/system/app/MIUIDeskClockGlobalS /system/app/
# mv -v -f ./dblot/system/app/MIUIFileExplorerGlobal /system/app/
# mv -v -f ./dblot/system/app/MIUIFrequentPhrase /system/app/
# mv -v -f ./dblot/system/app/MIUIGlobalLayout /system/app/
# mv -v -f ./dblot/system/app/MIUIGlobalPackageInstaller /system/app/
# mv -v -f ./dblot/system/app/MIUIGuardProviderGlobal /system/app/
# mv -v -f ./dblot/system/app/MIUIHealthGlobal /system/app/
# mv -v -f ./dblot/system/app/MIUIMiPicks /system/app/
# mv -v -f ./dblot/system/app/MIUINotes /system/app/
# mv -v -f ./dblot/system/app/MiuiPrintSpoolerBeta /system/app/
# mv -v -f ./dblot/system/app/MiuiScanner /system/app/
# mv -v -f ./dblot/system/app/MIUIScreenRecorderGlobal /system/app/
# mv -v -f ./dblot/system/app/MIUIScreenshot /system/app/
# mv -v -f ./dblot/system/app/MiuiSecurityAddGlobal /system/app/
# mv -v -f ./dblot/system/app/miuisystem /system/app/
# mv -v -f ./dblot/system/app/MIUISystemAppUpdater /system/app/
# mv -v -f ./dblot/system/app/MIUISystemUIPlugin /system/app/
# mv -v -f ./dblot/system/app/MIUIThemeManagerGlobal /system/app/
# mv -v -f ./dblot/system/app/MIUITouchAssistantGlobal /system/app/
# mv -v -f ./dblot/system/app/MIUIVideoPlayer /system/app/
# mv -v -f ./dblot/system/app/miuix /system/app/
# mv -v -f ./dblot/system/app/MiuixEditor_global /system/app/
# mv -v -f ./dblot/system/app/MIWallpaper /system/app/
# mv -v -f ./dblot/system/app/MSA-Global /system/app/
# mv -v -f ./dblot/system/app/NotificationCenter /system/app/
# mv -v -f ./dblot/system/app/PacProcessor /system/app/
# mv -v -f ./dblot/system/app/PartnerBookmarksProvider /system/app/
# mv -v -f ./dblot/system/app/PaymentService /system/app/
# mv -v -f ./dblot/system/app/PlayAutoInstallStubApp /system/app/
# mv -v -f ./dblot/system/app/PowerChecker /system/app/
# mv -v -f ./dblot/system/app/PowerKeeper /system/app/
# mv -v -f ./dblot/system/app/Sar_J20C /system/app/
# mv -v -f ./dblot/system/app/secretcode /system/app/
# mv -v -f ./dblot/system/app/SecureElement /system/app/
# mv -v -f ./dblot/system/app/SecurityCoreAdd /system/app/
# mv -v -f ./dblot/system/app/SensorTestTool_J20C /system/app/
# mv -v -f ./dblot/system/app/SimAppDialog /system/app/
# mv -v -f ./dblot/system/app/Stk /system/app/
# mv -v -f ./dblot/system/app/Updater /system/app/
# mv -v -f ./dblot/system/app/WallpaperBackup /system/app/
# mv -v -f ./dblot/system/app/WMService /system/app/
# mv -v -f ./dblot/system/app/XiaomiAccount /system/app/
# mv -v -f ./dblot/system/app/XiaomiServiceFrameworkGlobal /system/app/
# mv -v -f ./dblot/system/app/XiaomiSimActivateService /system/app/
# mv -v -f ./dblot/system/app/XMSFKeeperAll /system/app/

# mv -v -f ./dblot/system/data-app/XMRemoteController /system/data-app/

# mv -v -f ./dblot/system/priv-app/AuthManager /system/priv-app/
# mv -v -f ./dblot/system/priv-app/Backup /system/priv-app/
# mv -v -f ./dblot/system/priv-app/BackupRestoreConfirmation /system/priv-app/
# mv -v -f ./dblot/system/priv-app/barrage /system/priv-app/
# mv -v -f ./dblot/system/priv-app/BlockedNumberProvider /system/priv-app/
# mv -v -f ./dblot/system/priv-app/BuiltInPrintService /system/priv-app/
# mv -v -f ./dblot/system/priv-app/CalendarProvider /system/priv-app/
# mv -v -f ./dblot/system/priv-app/CallLogBackup /system/priv-app/
# mv -v -f ./dblot/system/priv-app/CellBroadcastLegacyApp /system/priv-app/
# mv -v -f ./dblot/system/priv-app/CleanMaster /system/priv-app/
# mv -v -f ./dblot/system/priv-app/CloudBackup /system/priv-app/
# mv -v -f ./dblot/system/priv-app/ContactsProvider /system/priv-app/
# mv -v -f ./dblot/system/priv-app/DocumentsUIGoogle /system/priv-app/
# mv -v -f ./dblot/system/priv-app/DownloadProvider /system/priv-app/
# mv -v -f ./dblot/system/priv-app/DownloadProviderUi /system/priv-app/
# mv -v -f ./dblot/system/priv-app/DynamicSystemInstallationService /system/priv-app/
# mv -v -f ./dblot/system/priv-app/ExternalStorageProvider /system/priv-app/
# mv -v -f ./dblot/system/priv-app/facebook-installer /system/priv-app/
# mv -v -f ./dblot/system/priv-app/facebook-services /system/priv-app/
# mv -v -f ./dblot/system/priv-app/FindDevice /system/priv-app/
# mv -v -f ./dblot/system/priv-app/FusedLocation /system/priv-app/
# mv -v -f ./dblot/system/priv-app/GooglePackageInstaller /system/priv-app/
# mv -v -f ./dblot/system/priv-app/InputDevices /system/priv-app/
# mv -v -f ./dblot/system/priv-app/LocalTransport /system/priv-app/
# mv -v -f ./dblot/system/priv-app/ManagedProvisioning /system/priv-app/
# mv -v -f ./dblot/system/priv-app/MediaProviderLegacy /system/priv-app/
# mv -v -f ./dblot/system/priv-app/MiLauncherGlobal /system/priv-app/
# mv -v -f ./dblot/system/priv-app/MIService /system/priv-app/
# mv -v -f ./dblot/system/priv-app/MISettings /system/priv-app/
# mv -v -f ./dblot/system/priv-app/MIShareGlobal /system/priv-app/
# mv -v -f ./dblot/system/priv-app/MiuiCamera /system/priv-app/
# mv -v -f ./dblot/system/priv-app/MiuiExtraPhoto /system/priv-app/
# mv -v -f ./dblot/system/priv-app/MiuiFreeformService /system/priv-app/
# mv -v -f ./dblot/system/priv-app/MIUIGalleryGlobal /system/priv-app/
# mv -v -f ./dblot/system/priv-app/MIUIGlobalMinusScreen /system/priv-app/
# mv -v -f ./dblot/system/priv-app/MIUIMusicGlobal /system/priv-app/
# mv -v -f ./dblot/system/priv-app/MIUISoundRecorderTargetSdk30Global /system/priv-app/
# mv -v -f ./dblot/system/priv-app/MiuiVpnDialogs /system/priv-app/
# mv -v -f ./dblot/system/priv-app/MIUIWeatherGlobal /system/priv-app/
# mv -v -f ./dblot/system/priv-app/MIUIYellowPageGlobal /system/priv-app/
# mv -v -f ./dblot/system/priv-app/MmsService /system/priv-app/
# mv -v -f ./dblot/system/priv-app/MtpService /system/priv-app/
# mv -v -f ./dblot/system/priv-app/MusicFX /system/priv-app/
# mv -v -f ./dblot/system/priv-app/NetworkPermissionConfigGoogle /system/priv-app/
# mv -v -f ./dblot/system/priv-app/NetworkStackGoogle /system/priv-app/
# mv -v -f ./dblot/system/priv-app/ONS /system/priv-app/
# mv -v -f ./dblot/system/priv-app/Provision /system/priv-app/
# mv -v -f ./dblot/system/priv-app/ProxyHandler /system/priv-app/
# mv -v -f ./dblot/system/priv-app/RtMiCloudSDK /system/priv-app/
# mv -v -f ./dblot/system/priv-app/SecurityCenter /system/priv-app/
# mv -v -f ./dblot/system/priv-app/SettingsProvider /system/priv-app/
# mv -v -f ./dblot/system/priv-app/SharedStorageBackup /system/priv-app/
# mv -v -f ./dblot/system/priv-app/Shell /system/priv-app/
# mv -v -f ./dblot/system/priv-app/SoundPicker /system/priv-app/
# mv -v -f ./dblot/system/priv-app/Tag /system/priv-app/
# mv -v -f ./dblot/system/priv-app/Telecom /system/priv-app/
# mv -v -f ./dblot/system/priv-app/TelephonyProvider /system/priv-app/
# mv -v -f ./dblot/system/priv-app/TeleService /system/priv-app/
# mv -v -f ./dblot/system/priv-app/Traceur /system/priv-app/
# mv -v -f ./dblot/system/priv-app/UserDictionaryProvider /system/priv-app/
